/*
 * FileMetadata Sharing API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package babji.sharesafe.api.models;

import lombok.*;

@Getter
@Setter
@Builder
@ToString
@AllArgsConstructor
@NoArgsConstructor
@EqualsAndHashCode
public class FileMetadata {

  private Long id;

  private String name;

  private String descr;

  private MalwareVerdictEnum malwareVerdict;

  private Long ownedBy;

  private String signature;


}
